services:
  ################################################################
  # Prepare infra for some tests.
  minio:
    image: minio/minio:${IMAGE_TAG_MINIO}
    container_name: minio
    hostname: minio
    environment:
      - "MINIO_ROOT_USER"
      - "MINIO_ROOT_PASSWORD"
      - "MINIO_SITE_REGION"
      - "MINIO_DOMAIN"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - e2e

  prepare_minio:
    image: minio/mc:${IMAGE_TAG_MINIO_MC}
    container_name: prepare_minio
    environment:
      - "MINIO_ROOT_USER"
      - "MINIO_ROOT_PASSWORD"
      - "S3_MINIO_KEY"
      - "S3_MINIO_KEY_SECRET"
      - "S3_MINIO_HOSTNAME"
      - "S3_MINIO_BUCKET"
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - "./scripts/prepare/prepare_minio.sh:/prepare_minio.sh"
    entrypoint: /prepare_minio.sh
    networks:
      - e2e

  ################################################################
  # Export gpbackman binary to shared volume.
  gpbackman-export:
    image: ${IMAGE_GPBACKMAN}
    container_name: gpbackman-export
    hostname: gpbackman-export
    volumes:
      - gpbackman_bin:/export
    entrypoint: ["/bin/sh","-c","cp /usr/bin/gpbackman /export/gpbackman && chmod 755 /export/gpbackman && sleep infinity"]
    networks:
      - e2e

  ################################################################
  greenplum:
    image: woblerr/greenplum:${IMAGE_TAG_GREENPLUM}
    container_name: greenplum
    hostname: greenplum
    depends_on:
      minio:
        condition: service_healthy
      prepare_minio:
        condition: service_completed_successfully
      gpbackman-export:
        condition: service_started
    environment:
      - "GREENPLUM_PASSWORD"
    volumes:
      - ./conf/gpbackup_s3_plugin.yaml:/home/gpadmin/gpbackup_s3_plugin.yaml
      - ./scripts/prepare/gpdb_init:/docker-entrypoint-initdb.d
      - ./scripts/prepare/prepare_gpdb_backups.sh:/home/gpadmin/prepare_gpdb_backups.sh
      - ./scripts/run_tests:/home/gpadmin/run_tests
      - ./src_data:/home/gpadmin/src_data
      - gpbackman_bin:/home/gpadmin/gpbackman
    networks:
      - e2e

networks:
  e2e:

volumes:
  gpbackman_bin:
