name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      build_platforms: "linux/amd64"
    steps:
      - name: Set up go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/coverage.out ./...
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "Etc/UTC"

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
        env:
          TZ: "Etc/UTC"

      - name: Install goveralls
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls

      - name: Submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/coverage.out
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
