name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      build_platforms: "linux/amd64"
    steps:
      - name: Set up go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/coverage.out ./...
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "Etc/UTC"

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
        env:
          TZ: "Etc/UTC"

      - name: Install goveralls
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls

      - name: Submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/coverage.out
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  goreleaser:
    needs: build
    runs-on: ubuntu-latest
    env: 
      goreleaser_version: "v1.20.0"
    permissions:
      contents: write
    steps:
      - name: Set up go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get ref
        id: vars
        run: |
          echo ::set-output name=ref::$(echo ${GITHUB_REF} | cut -d'/' -f3)

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          distribution: goreleaser
          version: ${{ env.goreleaser_version }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
